# Backstage (idp-portal). Image built by github.com/DSurya11/idp-portal CI.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
