apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-svc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DSurya11/idp-gitops
    targetRevision: HEAD
    path: apps/hello-svc/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        elbv2.k8s.aws/pod-readiness-gate-inject: enabled
